### PR TITLE
Ishan27596/converters

### PR DESCRIPTION
**Pull request by Ishan-Ravindu**

### CODE REVIEW

**Comment by ishan27596** [comment]
hey @jejopl,  

I have a problem with my code. 
in the index.js file, there is two function call (imported from temperatureConverter.js and lengthConverter.js)

`temperatureConverter(20, 1) `
`lengthConverter(20, "feet")`

i can read numbers (20,1) between <script></ script> tag ( inside temperatureConverter.js file) 

but i can't read string ("feet") value between <script></ script> tag ( inside lengthConverter.js file) 

simply
temperature Converter working properly (when using  arguments as numbers)
but length converter not working properly (when using  arguments as string)

need help for fix this🙏

**Comment by jejopl** [comment]
Hey @ishan27596, I will take a look on that, thanks!

**Comment by joshtom1** [comment]
hi @ishan27596 I looked at your original code before you switched from a string to an integer.

If you change
`		if(${queryUnit}==="feet"){`
to
`		if('${queryUnit}'==="feet"){`
it will work.

How to troubleshoot in chrome debugger:
**_Before_**
image

**_After_**
image

feet is not a variable. It should be a string.

**Comment by ishan27596** [comment]
@joshtom1 Thank you for helping🤝. now code working fine.

**Comment by jejopl** [comment]
Awesome, thanks @joshtom1! Sorry for the delay, I just got back from vacation and I didn't have time to check it out earlier

**Comment by jejopl** [comment]
@Ishan-Ravindu works great! Nice job! 😃👍 
The one thing, can you exclude `package-lock.json` files from this PR? Then I will merge your package

**Pull request closed without merging**
