### PR TITLE
Fixes & Improvements to currencyConverter package

### PR DESCRIPTION
**Pull request by threej-in**
image

- Fixed unnecessary calls to parseAnsNormalize function after query is triggered by storing the result to global variable

- Fixed unnecessary call to crypto API when only fiat conversion is requested. It will help reducing no of calls to API

- Fixed problem with thousand separator. Result shown in the below image.
image

- Using Google finance API for fiat conversion to get more accurate data

- Fixed problems with rounding conversions. Previously huge difference in rate resulted into 0 as toValue. For example: IRR to USD conversion returned 0. Result shown in the below image.
image

- Added two input fields in results for live conversion of requested pair for more interactivity.
image

- Also added a rate conversion pair reverse button in result.

### CODE REVIEW

**Comment by threej-in** [comment]
@treygrainger @jejopl Looking for your feedbacks on this PR.

**Comment by jejopl** [comment]
Great job @threej-in. It looks like you and another community members are trying to solve the same issue. Maybe you can co-work on this one?
https://github.com/PresearchOfficial/presearch-packages/pull/146

**Comment by threej-in** [comment]
Will work for sure, if they allow me to commit on their PR.

**Comment by jejopl** [comment]
Closing this one because this functionality were added in another PR

**Pull request closed without merging**
