### PR TITLE
Fixed some bugs and layout

### PR DESCRIPTION
**Pull request by jejopl**

### CODE REVIEW

**Comment by dskrenta** [comment]
Hey jejopl,

Thanks for continuing to work on your package! We actually had to make some updates to your package before we released since some of the conversions were reversed. It makes it easier for us to test your code and for you to keep your local copy of presearch-packages updated if you clone our main presearch-packages repository and make a branch instead of working from a fork. There were some other updates unrelated on the master branch as well so you will need to make a new branch from master on our copy. Once you move your updates into a branch on the main presearch-packages repository I can merge your updates in. We are still working on the documentation and it will most likely take a while to get it completely right and clear so thanks for bearing with us in these early stages.

**Comment by jejopl** [comment]
Thanks,@dskrenta, but I'm not allowed to push to the original repository. I don't know how to create a pull request from a copy (I didn't know that this is possible). I've always done this from a fork. Before I'm making any changes, I'm always syncing the fork.

I've created a new branch from a copy and I've tried to push it to the new branch, but I'm receiving this error:
```
remote: Permission to PresearchOfficial/presearch-packages.git denied to jejopl.
fatal: unable to access 'https://github.com/PresearchOfficial/presearch-packages.git/': The requested URL returned error: 403
```

**Comment by dskrenta** [comment]
Hey @jejopl, 

Thanks for letting me know, we'll get that error resolved. If you are syncing your fork it should be fine. I'll merge in your updates and let you know when they are deployed.

**Comment by jejopl** [comment]
Awesome, thanks for help @dskrenta :-)

**Pull request merged**
