### PR TITLE
Weather package

### PR DESCRIPTION
**Pull request by piwnik**
Initial commit of weather package

### CODE REVIEW

**Comment by jejopl** [comment]
Sorry for the late response @piwnik - I was on vacation recently
Great job overall! I've added some error handling - in case that API request will fail. Also, I've added an ability to save user preferences. When someone will choose "C" units, those units will be displayed next time, instead of "F"

A few things that can be improved:
1. When you click on the last day - there's no graph
image

2. Because we have a high amount of daily searches, and a fact that the API is limited, we may consider to use a local database (json file) with the cities list. So the package will be triggered only if there's a `weather` word inside query and when the next word is insice cities file

**Comment by jejopl** [comment]
Also, one more thing - IMO it will look better in light mode, when you will adjust the colors, from black to lighter gray 
image

**Comment by piwnik** [comment]
Hi,

Thank you for your feedback, and even improvement!
1. Will be fixed (haven't noticed that).
2. Here I have to clarify:
   a) Only queries like "weather London", "weather NewYork" will work, but
not "weather near me", "weather in London" or just "weather"? (unless
cities file will contain "in London" and "London")
   b) Which/how many cities should I include in json? It will be ok,
extract them from
https://raw.githubusercontent.com/lutangar/cities.json/master/cities.json
or use some other source for this?

**Comment by jejopl** [comment]
@piwnik I think that the file that you've found should be enough for now. You can include `weather` and `wearther in` and then look for the rest inside json file. About weather near me, I don't know the details but I imagine that they are using the IP address of the client, right?

In the setup that we currently have - it's not going to work, because on search engine, user's IP is not exposed to the node (node is returning search results and presearch-packages results).

**Comment by jejopl** [comment]
Thanks @piwnik! I'll review it shortly. Also, we had some discussion on the team and there's an option in Presearch that's allowing you to turn ON/OFF local search results. 
image

When someone will have local search result turned on, we will pass the geolocation to the packages as well. So we will be able to use `weather` query, and it will get the weather based on user's location. 
Also, there will be a way to change it manually

**Comment by piwnik** [comment]
@jejopl Responsive design implemented
WeatherPackageResponsive

**Comment by piwnik** [comment]
> 
Improved a bit (in my opinion) light scheme
image

**Comment by piwnik** [comment]
> Thanks @piwnik! I'll review it shortly. Also, we had some discussion on the team and there's an option in Presearch that's allowing you to turn ON/OFF local search results. image
> 
> When someone will have local search result turned on, we will pass the geolocation to the packages as well. So we will be able to use `weather` query, and it will get the weather based on user's location. Also, there will be a way to change it manually

Good, how I can get user location from in package?

**Comment by jejopl** [comment]
Great job @piwnik 👍 😃 
About user's location, it's not ready yet. I'm working on this one currently. Once it will be available I'll let you know

**Comment by jejopl** [comment]
@piwnik I've added geolocation to the test environment. To trigger it on, you need to add `geolocation` param to the url.
In this case, it will be `http://localhost:4000/weather?q=weather&geolocation=1` 

It has hardcoded data for London, but this will be the data that will be come to this package in production. Basically a city name and coords. 

There's one more thing that we will want to do before publishing this package - when the user will type `weather` as his query, and he will have geoLocation turned off, we want to add an ability to manually specify the location. Also, the ability to overwrite the city name, in case that the geoLocation will return the wrong city

**Comment by piwnik** [comment]
@jejopl Super! As I understand, you already implemented geolocation handling in package, custom location configuration will be implemented in settings, so nothing left for me now :)

**Comment by jejopl** [comment]
Yes, that's correct. Awesome job @piwnik! 
And sorry, this is a new functionality and it's not implemented yet into dev env. It's not even implemented in production - I'm currently working on this. Basically, there will be another option available for developers to save user's settings.

So for now, I have to finish it myself because we want to push this package to production on next week

**Pull request merged**
