### PR TITLE
PresearchNews package

### PR DESCRIPTION
**Pull request by piwnik**
Presearch recent odysee videos package, trigger examples:
pre news
presearch updates
presearch weekly
pre videos
...

prenews

### CODE REVIEW

**Comment by jejopl** [comment]
Nice! Good job, I like it @piwnik 👍 
Hmm I'm not sure about the medium articles. It may be too much but maybe you'll find a way to fit them in?

**Comment by jejopl** [comment]
Looks good! One thing, I've renamed the package to camel case, because this is what we are using for other packages.

**Comment by piwnik** [comment]
Awesome, thank you for fast review!!

**Comment by treygrainger** [comment]
@piwnik Thanks so much for the contribution. Just wanted to share and update here.

We're unfortunately holding off on pushing this out temporarily. I did an additional code review and noticed it's embedding third-party images (from Odyssee) directly on the search page. This allows Odyssee to see all IP addresses from users who search for Presearch news, leaking private query and IP information to them from end users.

Odysee's privacy policy isn't good at all, but regardless of this we don't want user info leaking from their browser to third parties like this.

We have an update to our image cache that is in progress and will hopefully be rolling out in a few weeks. At that time, we can safely roll this out, because we'll be able to intercept the image requests and replace them with cached versions from the Presearch domain.

Just wanted to give you and update here. Thanks for the contribution, and we look forward to getting it out as soon as we can.

Not sure if you're planning on also adding in Medium posts, but if so then we could even push it all out at the same time!

**Comment by piwnik** [comment]
@treygrainger @jejopl Thanks for update! I have some thoughts about images, after review few packages, I haven't found image cache usage/example, and as this is odyesee, decentralization and so on, so I just felt that this is OK, to use their images, I just picked in my point of view on that time the lesser evil. Now I understand, that it isn't ok. So as solution, I can suggest make pull request, where I download images from odysee on presearch/engine side, and return to user in base64 image format. But I feel, that isn't the real solution, because you mentioned "cached version of images on presearch domain", that will be way better, than return heavy search response with encoded images. So still, if package requires some changes form my side - I'm ready!

**Comment by treygrainger** [comment]
Hi @piwnik - that's a really good suggestion, and yeah - that would work. Only issue is that it might slow the search results down (because you're downloading all the images on every request). In practice, since the packages execute in parallel with the main search query, you've got some time to work with, though (at least 500-800ms) to get that all done before the search speed would be impacted.

However, given that this package is only loaded on a very specific query for Presearch news, that's not a big deal at all as long as it can be done in reasonable time for a real-time search. Note: the package will time out (return no results) if it doesn't return fast enough.

So yeah, I think if you can hit the odyssee endpoint, get all the thumbnails links and download them all async in parallel, and return them as base64, that that's a good option.

Then, once the image cache is available, we can revert back to how you have it and leverage the much faster, cached version.

Sounds like a plan? If so, please go for it, and we'll review when you send the PR back over!

Thanks!

**Comment by piwnik** [comment]
Done, check it here https://github.com/PresearchOfficial/presearch-packages/pull/181 !

**Comment by piwnik** [comment]
> Not sure if you're planning on also adding in Medium posts, but if so then we could even push it all out at the same time!

I'm thinking to try draw some sketches, then will see if it fits. Unfortunately drawing/designing took most of time, designing isn't my strongest skill :/

**Comment by piwnik** [comment]
> you've got some time to work with, though (at least 500-800ms)

Oh, then it probably will not work, because I can't speed up images download from odysee or blockchain (from blockchain is twice slower than odysee) :/

**Comment by treygrainger** [comment]
@piwnik I left a comment on the new PR. It's loading all 6 images serially. I think if you use a promises to make it run in parallel / async then the total tile should be reduced by 83%.

**Pull request merged**
